// 200+ rotating prompt chips for the /ai page.
// Pulled from a deterministic seed per session, reshuffled on demand.

export const ASK_REJN_SUGGESTIONS: string[] = [
  // Daily weather
  "Will it rain tomorrow?",
  "What should I wear today?",
  "Is it umbrella weather?",
  "Should I bike to work?",
  "Will it be sunny this weekend?",
  "How cold will tonight be?",
  "Do I need a jacket today?",
  "Is it shorts weather yet?",
  "When does the rain stop?",
  "Will it snow this week?",
  "Is there frost tonight?",
  "How windy is it right now?",
  "When is the next dry day?",
  "Will it be foggy tomorrow morning?",
  "Is there a storm coming?",
  "What time does it start raining?",
  "When will the sun come out?",
  "How warm will Saturday be?",
  "Is it pool weather tomorrow?",
  "Will the rain affect my run?",

  // Plans & lifestyle
  "Best day to do laundry this week?",
  "Can I plan a picnic for Sunday?",
  "Is tomorrow a beach day?",
  "Will my BBQ get rained on?",
  "Good weather for hiking this weekend?",
  "When should I water my plants?",
  "Is it safe to drive tonight?",
  "Will my flight be delayed?",
  "Should I bring sunglasses today?",
  "Is it golf weather Saturday?",
  "Best day this week for a date outside?",
  "Can I wash my car today?",
  "Should I plan an indoor day tomorrow?",
  "Is the surf any good this weekend?",
  "Will it be a good night for stargazing?",
  "Should I cancel my outdoor plans?",
  "Best time of day to go for a walk?",
  "Is it good weather for photography?",
  "Should I bring layers tomorrow?",
  "Is it sandal weather?",

  // Hyperlocal / micro
  "How's the weather on my exact street?",
  "Will it rain in the next 15 minutes?",
  "Will it clear up in an hour?",
  "Any rain in the next 2 hours?",
  "Is the rain heading toward me?",
  "Will the wind pick up later?",
  "Will it feel colder than it looks?",
  "What's the wind chill right now?",
  "How muggy will it feel today?",
  "What's the UV like at noon?",

  // Predictions & game
  "How do predictions work?",
  "Tips to win prediction battles?",
  "What's my prediction streak?",
  "How do I climb the leaderboard?",
  "Best strategy for tomorrow's prediction?",
  "What temperature should I guess tomorrow?",
  "What's a safe rain prediction?",
  "How are points calculated?",
  "What's a streak multiplier?",
  "How do I challenge a friend?",
  "What's the most common rookie mistake?",
  "Will the bot beat me tomorrow?",
  "Should I bet on rain or shine?",
  "Best day to gamble on a big prediction?",
  "How do I unlock achievements?",

  // Features
  "What is DryRoutes?",
  "How does Rejn SkyCam work?",
  "What's the ensemble forecast?",
  "Why do I get different forecasts?",
  "How accurate is Rejn?",
  "What weather models do you use?",
  "How do I save a location?",
  "How do I turn on notifications?",
  "Can I track pollen here?",
  "How do I share my forecast?",
  "What's Weather Wrapped?",
  "How do streak challenges work?",
  "What's the Rainz Score?",
  "What are weather reactions?",
  "How do I embed a widget?",

  // Health & allergies
  "Is pollen high today?",
  "Birch pollen forecast for tomorrow?",
  "Will my allergies be bad this weekend?",
  "Is the air quality safe to run in?",
  "AQI right now?",
  "Best time to be outside with allergies?",
  "Is it migraine weather?",
  "Will pressure drop tonight?",
  "Should I wear a mask outside today?",
  "Grass pollen levels this week?",

  // Astronomy / sky
  "What phase is the moon tonight?",
  "When does the sun set today?",
  "Will I see a sunrise tomorrow?",
  "Any chance of northern lights tonight?",
  "Can I see the stars tonight?",
  "When does it get dark?",
  "Will there be a full moon soon?",
  "What's golden hour today?",
  "Best night this week for stargazing?",
  "Is the moon up right now?",

  // Travel & cities
  "Weather in Copenhagen tomorrow?",
  "How's the weather in Stockholm right now?",
  "Oslo forecast for the weekend?",
  "Helsinki temperature tomorrow?",
  "Reykjavik weather next week?",
  "Is it raining in Aarhus?",
  "Tromsø weather tonight?",
  "Malmö forecast?",
  "Bergen rain chance?",
  "Should I pack warm for Iceland?",
  "What city has the best weather right now?",
  "Where's the sun in Scandinavia today?",
  "Coldest Nordic capital tomorrow?",
  "Where will it snow first this season?",
  "Best Scandinavian city this weekend?",

  // Seasonal
  "When does autumn really start?",
  "First snow forecast?",
  "Will it be a white Christmas?",
  "When will it warm up for spring?",
  "Is summer over?",
  "When do leaves start falling?",
  "First frost prediction?",
  "When does winter end?",
  "Hottest day of summer prediction?",
  "Coldest day of winter prediction?",
  "Will there be a heatwave this summer?",
  "Storm season starting soon?",

  // Fun facts & curiosity
  "Tell me a weird weather fact",
  "Why is the sky blue?",
  "How does lightning work?",
  "What causes rainbows?",
  "Why does it snow but not rain in winter?",
  "Can it be too cold to snow?",
  "What's the loudest thunder ever?",
  "Why does rain smell good?",
  "How fast can wind get?",
  "Tell me a hurricane fact",
  "How are tornadoes formed?",
  "What's the biggest snowflake ever?",
  "How do clouds float?",
  "Why is humidity sticky?",
  "Tell me a fun cloud fact",
  "Surprise me with a weather fact",
  "Most extreme weather ever recorded?",
  "Coldest place on Earth?",
  "Hottest place on Earth?",
  "Weirdest weather phenomenon?",
  "Tell me about ball lightning",
  "What is a sundog?",
  "Explain a polar vortex",
  "What is a derecho?",
  "What's a bomb cyclone?",
  "Why do hurricanes have names?",
  "Roast my hometown's weather",
  "Funniest weather pun?",

  // Mascot / casual chat
  "Hey Rejn 👋",
  "How are you today?",
  "Tell me a joke",
  "Tell me a weather joke",
  "What's your favorite type of weather?",
  "Do you ever sleep?",
  "Sing me a rain song",
  "What's the vibe today?",
  "Hype me up for the day",
  "Cheer me up, it's raining",
  "Tell me a cozy weather story",
  "Recommend a song for this weather",
  "Recommend a movie for a rainy day",
  "Recommend a snack for cold days",
  "Suggest an outfit for today",
  "What's a good rainy-day playlist?",
  "Make me smile",
  "Drop a wholesome weather quote",

  // Productivity / decisions
  "Should I work from home today?",
  "Best day this week to schedule a meeting outside?",
  "When should I leave to avoid the rain?",
  "Is it worth biking today?",
  "Will traffic be bad in this weather?",
  "Should I charge my umbrella forecast?",
  "Plan my week around the weather",
  "Best day for a long run?",
  "Best day for a chill indoor day?",
  "Optimal time to walk the dog today?",

  // Climate / curiosity
  "Is this normal for the season?",
  "How does this compare to last year?",
  "Is climate change affecting this week?",
  "Hottest year on record?",
  "Is Scandinavia getting warmer?",
  "When was the last big storm here?",
  "What's the average temp this month?",
  "How rare is this weather?",

  // Niche
  "Is it good weather to fly a drone?",
  "Can I paddle board tomorrow?",
  "Is the lake going to be calm?",
  "Will the snow stick to the ground?",
  "Are ski conditions any good?",
  "Is it sledding weather?",
  "Are roads icy tonight?",
  "Will my window steam up tomorrow?",
  "Should I bring a rain cover for my bag?",
  "Is it bad hair day weather?",
  "Static electricity warning today?",
  "Good day to fly a kite?",
];

/** Fisher–Yates shuffle (immutable). */
export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function pickSuggestions(count = 4): string[] {
  return shuffle(ASK_REJN_SUGGESTIONS).slice(0, count);
}
