// 200 funny, weird, and crazy weather facts for the splash screen
export const WEATHER_FACTS: string[] = [
  "Lightning is 5x hotter than the surface of the sun. 🔥",
  "A single cloud can weigh more than a million pounds. ☁️",
  "Raindrops are shaped like tiny hamburger buns, not teardrops. 🍔",
  "It once rained fish in Honduras. Actual. Fish. 🐟",
  "Snowflakes can take up to an hour to fall from cloud to ground. ❄️",
  "The fastest wind ever recorded was 253 mph in Australia. 💨",
  "Antarctica is technically the world's largest desert. 🏜️",
  "A bolt of lightning contains enough energy to toast 100,000 slices of bread. 🍞",
  "It rains diamonds on Neptune and Uranus. 💎",
  "The wettest place on Earth gets 467 inches of rain a year. ☔",
  "Sand from the Sahara regularly travels to the Amazon. 🌍",
  "Tornadoes can cause sound waves humans can't even hear. 🌪️",
  "The coldest temperature ever recorded was -128.6°F in Antarctica. 🥶",
  "A hurricane releases the energy of 10,000 nuclear bombs. 💥",
  "Frogs have actually rained from the sky multiple times. 🐸",
  "Lightning strikes the Earth about 100 times every second. ⚡",
  "Some snowflakes are bigger than your face. ❄️",
  "Mount Waialeale in Hawaii has rain 335 days a year. 🌧️",
  "Dust storms on Mars can cover the entire planet. 🔴",
  "The Sahara was once a lush green jungle. 🌴",
  "A rainbow at night is called a moonbow. 🌙",
  "Snow isn't actually white — it's translucent. 👻",
  "The largest hailstone ever was the size of a volleyball. 🏐",
  "Cows lie down before a storm. Sometimes. Maybe. 🐄",
  "Thunder is the sound of air exploding from lightning heat. 🔊",
  "Venus has clouds made of sulfuric acid. 🧪",
  "It snowed in the Sahara desert in 2018. 🏜️❄️",
  "A waterspout is basically a tornado that wandered out to sea. 🌊",
  "The eye of a hurricane can be 30 miles wide. 👁️",
  "Lightning can strike the same place twice. The Empire State gets hit ~25x/year. 🏙️",
  "There are 2,000 thunderstorms happening on Earth right now. ⛈️",
  "Snow can fall when it's above freezing. Physics is weird. 🤷",
  "The driest place on Earth hasn't seen rain in 2 million years. 🏜️",
  "Hailstones can fall at over 100 mph. 🥎",
  "Some lightning strikes are positive — and 10x more powerful. ➕",
  "Fog is just a cloud that touched the ground. 🌫️",
  "A 'thundersnow' is a snowstorm with thunder and lightning. ⛈️❄️",
  "Earth's atmosphere weighs 5.5 quadrillion tons. ⚖️",
  "The smell after rain has a name: petrichor. 👃",
  "Jupiter has a storm bigger than Earth that's lasted 350+ years. 🪐",
  "Sprites are red lightning that shoot UP into space. 🧚",
  "The wind on Saturn blows at 1,100 mph. Casual. 💨",
  "A microburst can flip airplanes. Yikes. ✈️",
  "Snow rollers are nature's snowballs. They roll themselves. ⚪",
  "Ball lightning exists, but no one knows how. 🔮",
  "The hottest temperature recorded on Earth was 134°F in Death Valley. 🥵",
  "Tornado Alley is shifting east. 🌪️",
  "Penguins can survive -76°F winds. 🐧",
  "Rainbows are actually full circles — we just see half. 🌈",
  "It rains methane on Saturn's moon Titan. 🌑",
  "An iceberg can be older than the Roman Empire. 🧊",
  "St. Elmo's Fire is a real weather phenomenon, not just a movie. 💙",
  "The Great Smog of 1952 killed 12,000 people in London. 😶‍🌫️",
  "Moon halos predict rain about 70% of the time. 🌕",
  "Crickets chirp faster when it's warmer. 🦗",
  "Hurricanes spin opposite directions in different hemispheres. 🌀",
  "A lightning strike heats air to 50,000°F. 🌡️",
  "Mammatus clouds look like cotton candy bubbles. 🍡",
  "The Atacama Desert had lakes for the first time in 500 years in 2015. 💧",
  "Ice can be hot — 'hot ice' exists at high pressures. 🔥🧊",
  "Snow makes everything quieter — it absorbs sound. 🤫",
  "Tornadoes can pluck feathers off chickens. 🐔",
  "There's a weather station on top of Mt. Everest. 🏔️",
  "Frost flowers grow on plants in late autumn. 🌸",
  "A fogbow is a rainbow made of fog. 🤍",
  "The biggest snowflake ever was 15 inches across. ❄️",
  "Cape Disappointment, WA is foggy 106 days a year. ☁️",
  "Hurricane names get retired if they're really bad. 📜",
  "Lake Maracaibo has lightning 297 nights a year. ⚡",
  "A derecho is a 'land hurricane.' Yes, that's real. 🌬️",
  "Snow once fell in Miami in 1977. ❄️🌴",
  "The atmosphere is about 100km thick. So... thin. 🌍",
  "Dew can collect enough to drink in survival situations. 💧",
  "Wind chill can make 10°F feel like -30°F. 🥶",
  "Some clouds glow at night — they're called noctilucent. ✨",
  "Smoke from Australian fires reached the stratosphere in 2020. 🔥",
  "Ice spikes can grow upwards out of frozen water. ⬆️",
  "There's a rare weather event called 'diamond dust.' 💎",
  "Lightning creates ozone — that's the smell after a storm. 🌬️",
  "A bomb cyclone is meteorology's most dramatic name. 💣",
  "The Mariana Trench has its own weather patterns. 🌊",
  "Snow fleas exist. They jump on snow. 🪲",
  "Volcanic lightning is a real, terrifying thing. 🌋⚡",
  "The Sun heats Earth unequally — that's why we have weather. ☀️",
  "Wind has a smell — it's called 'ozone' before storms. 🌪️",
  "A 'haboob' is a giant wall of sand. 🏜️",
  "Catatumbo lightning happens 10 hours a night. ⚡",
  "Roll clouds look like a giant tube rolling at you. 🎯",
  "Some hurricanes have created tornadoes inside themselves. 🌪️🌀",
  "Hailstones grow in layers, like onions. 🧅",
  "Greenland's ice sheet is melting 7x faster than in the 90s. 🌍",
  "The jet stream can blow at 275 mph. ✈️",
  "Asperitas clouds were officially classified in 2017. 🌊",
  "There's a 'Cloud Appreciation Society' with 60,000+ members. 🤓",
  "Pancake ice forms on calm seas in winter. 🥞",
  "Freezing rain can take down entire power grids. 💡",
  "The world's largest snowman was 122 feet tall. ⛄",
  "A 'snownado' is exactly what it sounds like. 🌪️❄️",
  "Drought has its own scale: D0 to D4. 📊",
  "Sundogs are bright spots beside the sun. 🌞",
  "The 1816 'Year Without a Summer' had snow in July. ❄️",
  "Thunder can be heard up to 25 miles away. 🔊",
  "A sea breeze front can trigger thunderstorms. 🌊⛈️",
  "Cumulonimbus clouds can reach 12 miles high. ☁️",
  "Polar vortexes are normal — they just sometimes wander. 🌀",
  "Tornadoes can be invisible until they pick up debris. 👻",
  "Greenland is mostly ice, but used to be green. Hence the name (sort of). 🟢",
  "A 'gustnado' is a small whirlwind from a thunderstorm. 💨",
  "Snow has been recorded in all 50 US states. 🇺🇸",
  "Hurricanes need water at least 80°F to form. 🌡️",
  "Cumulus clouds = fair weather. Cumulonimbus = run. ☁️→⛈️",
  "Russia has a town called 'Oymyakon' where it hits -90°F. 🥶",
  "Dust devils happen on Mars too. 👹",
  "The Bermuda Triangle has more storms than its surroundings. 🔺",
  "Rainbows have 7 colors but actually contain millions. 🌈",
  "Some clouds smell sweet. Others smell like fish. 🐟",
  "Lightning rods don't attract lightning — they redirect it. ⚡",
  "Frost can form when air is above freezing. 🥶",
  "Ice ages happen every 100,000 years roughly. 🦣",
  "A 'whiteout' can disorient you in seconds. ⚪",
  "The Pineapple Express is a real weather pattern. 🍍",
  "Auroras happen on other planets too. 🌌",
  "Earthquakes can change the weather slightly. 🌍",
  "Tropical cyclone, hurricane, typhoon — all the same thing. 🌀",
  "Sandstorms can be seen from space. 🛰️",
  "Snowflakes always have 6 sides. Always. ❄️",
  "Hailstones have been found with frogs frozen inside. 🐸",
  "Heat lightning is just regular lightning very far away. ⚡",
  "Some places get '24-hour daylight' for months. ☀️",
  "Cherrapunji, India once got 366 inches of rain in one month. 🌧️",
  "Snow can be pink. It's called 'watermelon snow.' 🍉",
  "A virga is rain that evaporates before hitting the ground. 💨",
  "The Coriolis effect is why hurricanes spin. 🌀",
  "Some snowstorms produce thundersnow with blue lightning. 💙",
  "Earth's magnetic field protects us from solar wind. 🛡️",
  "Iridescent clouds shimmer like soap bubbles. 🌈",
  "Lenticular clouds look like UFOs. 🛸",
  "Dew point matters more than humidity for comfort. 💧",
  "Sun pillars are vertical light beams from the sun. 🌞",
  "A 'green flash' at sunset is real and rare. 💚",
  "Anti-crepuscular rays point AWAY from the sun. ☀️",
  "El Niño can change weather across the entire planet. 🌊",
  "La Niña is El Niño's cooler sibling. 🥶",
  "The Atlantic hurricane season peaks in September. 📅",
  "Rain has been falling on Earth for 4 billion years. 🌧️",
  "Some glaciers move 150 feet per day. 🧊",
  "The Mpemba effect: hot water can freeze faster than cold. 🤯",
  "Drizzle drops are smaller than 0.5mm. 💧",
  "Hurricanes can give birth to baby hurricanes. 👶🌀",
  "The Tunguska Event in 1908 may have been a meteor — or weather. ☄️",
  "Hoarfrost looks like crystal forests. 🌲",
  "Glaze ice can crush trees. 🌳",
  "The Beaufort scale measures wind from 0 to 12. 🌬️",
  "Some clouds form over mountains — orographic clouds. ⛰️",
  "Tornadoes can stay on the ground for over 100 miles. 🛣️",
  "Hailstorms have damaged airplanes mid-flight. ✈️",
  "Freezing fog coats everything in white. 🌫️",
  "The Met Office in the UK has been forecasting since 1854. 📡",
  "Forecasts are about 90% accurate at 5 days out. 📊",
  "Weather satellites orbit 22,236 miles above Earth. 🛰️",
  "Doppler radar can spot rotation inside storms. 📡",
  "A barometer measures air pressure. 🎚️",
  "Hygrometers measure humidity. 💦",
  "Anemometers measure wind speed. 🎐",
  "Weather balloons reach 100,000+ feet. 🎈",
  "Stratosphere temperatures can reach -76°F. 🥶",
  "The mesosphere is where meteors burn up. ☄️",
  "The thermosphere can hit 4,500°F. 🔥",
  "There's a layer called the 'ionosphere' full of charged particles. ⚡",
  "Aurora Borealis = north. Aurora Australis = south. 🌍",
  "Auroras are caused by solar wind hitting our atmosphere. 💨",
  "Some lightning happens entirely INSIDE clouds. ☁️⚡",
  "Cloud-to-ground lightning is only 25% of all strikes. ⚡",
  "Snowfall reduces visibility more than rain. 👁️",
  "Black ice is invisible, deadly, and named for asphalt. 🖤",
  "Rime ice forms on the windward side of objects. 🧊",
  "Graupel is soft hail that looks like styrofoam. 🟪",
  "Sleet is rain that froze before landing. 🥶",
  "A nor'easter brings massive snow to the US East Coast. 🌨️",
  "The Mistral is a famous cold wind in France. 🇫🇷",
  "Foehn winds can melt feet of snow in hours. 🌡️",
  "Chinooks are 'snow eaters' in the Rockies. 🌬️",
  "Santa Ana winds make California fires worse. 🔥",
  "Monsoons reverse direction with the seasons. 🔄",
  "The ITCZ is a permanent storm belt near the equator. 🌍",
  "Trade winds blow from east to west near the equator. 💨",
  "Westerlies blow from west to east in mid-latitudes. ➡️",
  "The Roaring Forties are notorious sailing winds. ⛵",
  "Cold fronts move 2x faster than warm fronts. 🏃",
  "Occluded fronts happen when a cold front catches a warm one. 💑",
  "Stationary fronts just sit there. 😴",
  "Cyclones spin counterclockwise in the Northern Hemisphere. 🔄",
  "Anticyclones bring fair weather. ☀️",
  "High pressure = sinking air = clear skies. 📉",
  "Low pressure = rising air = clouds and storms. 📈",
  "The lowest pressure ever was 870 mb in Typhoon Tip. 🌀",
  "Typhoon Tip was the size of half the US. 🇺🇸",
  "A 'firenado' is a tornado made of fire. 🔥🌪️",
  "Bioluminescent algae glow before storms sometimes. ✨",
  "Birds fly lower before storms — denser air. 🦅",
  "Bees go home when bad weather is coming. 🐝",
  "Sharks dive deep before hurricanes. 🦈",
  "Cats reportedly clean behind their ears before rain. 🐱",
  "Pinecones close up when humidity rises. 🌰",
  "Seaweed gets soft before rain — old sailor trick. 🌿",
  "Ancient Greeks named 12 winds. 🏛️",
  "The word 'hurricane' comes from a Mayan storm god. 🌀",
  "Rainz the app loves you. Stay dry out there. 💙",
];

export function getRandomWeatherFact(): string {
  return WEATHER_FACTS[Math.floor(Math.random() * WEATHER_FACTS.length)];
}
