import { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';

export type Language = 'en-GB' | 'en-US' | 'da' | 'sv' | 'no' | 'fr' | 'it' | 'boomer';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  'en-GB': {
    // Header
    'app.tagline': 'Aiming to be the best weather app.',
    'header.signIn': 'Sign In',
    'search.placeholder': 'Search for a location...',
    'search.searching': 'Searching...',
    'search.noResults': 'No locations found',
    
    // Weather
    'weather.welcome': 'Welcome to Rainz',
    'weather.searchLocation': 'Search for a location above or allow location access',
    'weather.failed': 'Failed to load weather data',
    'weather.tryAgain': 'Try Again',
    'weather.demoData': 'Demo Data',
    'weather.demoMessage': 'API keys needed for real data',
    'weather.refresh': 'Refresh',
    'weather.locationCard': 'Location Card',
    'weather.myLocation': 'My Location',
    'weather.checkConnection': 'Please check your connection and try again',
    
    // Weather metrics
    'weather.wind': 'Wind',
    'weather.visibility': 'Visibility',
    'weather.feelsLike': 'Feels like',
    'weather.humidity': 'Humidity',
    'weather.pressure': 'Pressure',
    'weather.uvIndex': 'UV Index',
    
    // Time
    'time.goodMorning': 'Good Morning!',
    'time.dismiss': 'Dismiss',
    'time.today': 'Today',
    'time.tomorrow': 'Tomorrow',
    
    // Morning Review
    'morning.title': 'AI Morning Review',
    'morning.generating': 'Generating your morning briefing...',
    'morning.generate': 'Generate AI Morning Briefing',
    'morning.outfit': 'What to Wear:',
    'morning.pollenAlerts': 'Pollen Alerts',
    'morning.activities': 'Activities:',
    'morning.keyInsight': 'Key Insight:',
    
    // Settings
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.language': 'Language',
    'settings.signOut': 'Sign Out',
    'settings.enableNotifications': 'Enable Notifications',
    'settings.testNotification': 'Send Test Notification',
    'settings.cardVisibility': 'Card Visibility',
    'settings.cardOrder': 'Card Order',
    'settings.save': 'Save',
    'settings.customise': 'Customise your weather app experience',
    'settings.temperatureUnits': 'Temperature Units',
    'settings.useCelsius': 'Use Celsius (°C)',
    'settings.currentlyFahrenheit': 'Currently using Fahrenheit (°F)',
    'settings.currentlyCelsius': 'Currently using Celsius (°C)',
    'settings.reset': 'Reset',
    'settings.reloadChanges': 'Reload to activate changes.',
    'settings.languageChanged': 'Language changed',
    'settings.changedTo': 'Changed to',
    
    // Pollen
    'pollen.title': 'Pollen Forecast',
    'pollen.track': 'Track Allergies',
    'pollen.low': 'Low',
    'pollen.moderate': 'Moderate',
    'pollen.high': 'High',
    'pollen.veryHigh': 'Very High',
    'pollen.pollenIndex': 'Pollen Index',
    'pollen.hourlyForecast': '24-Hour Forecast',
    'pollen.tenDayForecast': '10-Day Forecast',
    'pollen.detailedMetrics': 'Detailed Metrics',
    'pollen.userRoutines': 'User Routines',
    'pollen.liveData': 'Live seasonal allergy data',
    'pollen.noData': 'No pollen data available',
    'pollen.locationRequired': 'Location data required',
    'pollen.trackAllergy': 'Track Allergy',
    'pollen.addAllergy': 'Add Allergy to Track',
    'pollen.allergen': 'Allergen',
    'pollen.allergenPlaceholder': 'e.g. Grass, Birch, Ragweed',
    'pollen.sensitivityLevel': 'Sensitivity Level',
    'pollen.mild': 'Mild',
    'pollen.severe': 'Severe',
    'pollen.addAllergyButton': 'Add Allergy',
    'pollen.currentSeason': 'Current Season Pollen',
    'pollen.active': 'active',
    'pollen.yourTracked': 'Your Tracked Allergies',
    'pollen.scale': 'Pollen Scale:',
    'pollen.scaleInfo': '0 = No risk • 1-2 = Low • 3-5 = Medium • 6-8 = High • 9+ = Very High',
    'pollen.alertInfo': 'Red alerts for your tracked allergies when levels may affect you',
    'pollen.adviceInfo': 'Higher numbers indicate increased pollen concentration. Consider limiting outdoor activities during high pollen periods.',
    'pollen.noRisk': 'No risk',
    'pollen.medium': 'Medium',
    'pollen.earlySpring': 'Early Spring',
    'pollen.spring': 'Spring',
    'pollen.lateSpring': 'Late Spring/Summer',
    'pollen.lateSummer': 'Late Summer',
    'pollen.springSummer': 'Spring/Summer',
    'pollen.autumn': 'Autumn',
    'pollen.alreadyTracked': 'You already have this allergy tracked',
    'pollen.addFailed': 'Failed to add allergy',
    'pollen.addSuccess': 'Allergy added successfully',
    'pollen.removeFailed': 'Failed to remove allergy',
    'pollen.removeSuccess': 'Allergy removed',
    
    // Footer
    'footer.dataFrom': 'Data from',
    'footer.disclaimer': 'We are not to be held accountable for any inaccuracies or wrong claims.',
    'footer.about': 'About',
    'footer.blog': 'Blog',
    'footer.download': 'Download',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.dataPrivacy': 'Data & Privacy Settings',
    'footer.copyright': '© 2025-{year} Rainz. All rights reserved.',
    
    // Cards & UI
    'card.tenDay': '10-Day Forecast',
    'card.hourly': '24-Hour Forecast',
    'card.hourlyTap': 'Tap any hour for details',
    'card.showLess': 'Show Less',
    'card.showAll': 'Show All 10 Days',
    'card.hourlyBreakdown': 'Hourly Breakdown',
    'card.weatherMap': 'Weather Map',
    'card.airQuality': 'Air Quality Index',
    'card.sunMoon': 'Sun & Moon',
    'card.uvIndex': 'UV Index',
    'card.sunrise': 'Sunrise',
    'card.sunset': 'Sunset',
    'card.daylight': 'Daylight',
    'card.moonRise': 'Rise',
    'card.moonSet': 'Set',
    'card.moonPhase': 'Phase',
    'card.precipitation': 'Precipitation',
    'card.opacity': 'Opacity',
    'card.past': 'Past',
    'card.forecast': 'Forecast',
    'card.tempHeatmap': 'Temperature Heatmap',
    'card.windLayer': 'Wind Speed Layer',
    
    // Streaks
    'streak.day': 'day',
    'streak.days': 'days',
    'streak.current': 'Current streak',
    'streak.best': 'best',
    'streak.visit': 'visit',
    'streak.visits': 'visits',
    
    // UV descriptions
    'uv.low': 'Low - No protection needed',
    'uv.moderate': 'Moderate - Some protection needed',
    'uv.high': 'High - Wear sunscreen',
    'uv.veryHigh': 'Very High - Extra protection needed',
    'uv.extreme': 'Extreme - Avoid sun exposure',
    
    // Languages
    'language.en-GB': 'British English',
    'language.en-US': 'American English',
    'language.da': 'Dansk',
    'language.sv': 'Svenska',
    'language.no': 'Norsk',
    'language.fr': 'Français',
    'language.it': 'Italiano',
    'language.boomer': '👴 Boomer',
  },
  'en-US': {
    // Header
    'app.tagline': 'Aiming to be the best weather app.',
    'header.signIn': 'Sign In',
    'search.placeholder': 'Search for a location...',
    'search.searching': 'Searching...',
    'search.noResults': 'No locations found',
    
    // Weather
    'weather.welcome': 'Welcome to Rainz',
    'weather.searchLocation': 'Search for a location above or allow location access',
    'weather.failed': 'Failed to load weather data',
    'weather.tryAgain': 'Try Again',
    'weather.demoData': 'Demo Data',
    'weather.demoMessage': 'API keys needed for real data',
    'weather.refresh': 'Refresh',
    'weather.locationCard': 'Location Card',
    'weather.myLocation': 'My Location',
    'weather.checkConnection': 'Please check your connection and try again',
    
    // Weather metrics
    'weather.wind': 'Wind',
    'weather.visibility': 'Visibility',
    'weather.feelsLike': 'Feels like',
    'weather.humidity': 'Humidity',
    'weather.pressure': 'Pressure',
    'weather.uvIndex': 'UV Index',
    
    // Time
    'time.goodMorning': 'Good Morning!',
    'time.dismiss': 'Dismiss',
    'time.today': 'Today',
    'time.tomorrow': 'Tomorrow',
    
    // Morning Review
    'morning.title': 'AI Morning Review',
    'morning.generating': 'Generating your morning briefing...',
    'morning.generate': 'Generate AI Morning Briefing',
    'morning.outfit': 'What to Wear:',
    'morning.pollenAlerts': 'Pollen Alerts',
    'morning.activities': 'Activities:',
    'morning.keyInsight': 'Key Insight:',
    
    // Settings
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.language': 'Language',
    'settings.signOut': 'Sign Out',
    'settings.enableNotifications': 'Enable Notifications',
    'settings.testNotification': 'Send Test Notification',
    'settings.cardVisibility': 'Card Visibility',
    'settings.cardOrder': 'Card Order',
    'settings.save': 'Save',
    'settings.customise': 'Customize your weather app experience',
    'settings.temperatureUnits': 'Temperature Units',
    'settings.useCelsius': 'Use Celsius (°C)',
    'settings.currentlyFahrenheit': 'Currently using Fahrenheit (°F)',
    'settings.currentlyCelsius': 'Currently using Celsius (°C)',
    'settings.reset': 'Reset',
    'settings.reloadChanges': 'Reload to activate changes.',
    'settings.languageChanged': 'Language changed',
    'settings.changedTo': 'Changed to',
    
    // Pollen
    'pollen.title': 'Pollen Forecast',
    'pollen.track': 'Track Allergies',
    'pollen.low': 'Low',
    'pollen.moderate': 'Moderate',
    'pollen.high': 'High',
    'pollen.veryHigh': 'Very High',
    'pollen.pollenIndex': 'Pollen Index',
    'pollen.hourlyForecast': '24-Hour Forecast',
    'pollen.tenDayForecast': '10-Day Forecast',
    'pollen.detailedMetrics': 'Detailed Metrics',
    'pollen.userRoutines': 'User Routines',
    'pollen.liveData': 'Live seasonal allergy data',
    'pollen.noData': 'No pollen data available',
    'pollen.locationRequired': 'Location data required',
    'pollen.trackAllergy': 'Track Allergy',
    'pollen.addAllergy': 'Add Allergy to Track',
    'pollen.allergen': 'Allergen',
    'pollen.allergenPlaceholder': 'e.g. Grass, Birch, Ragweed',
    'pollen.sensitivityLevel': 'Sensitivity Level',
    'pollen.mild': 'Mild',
    'pollen.severe': 'Severe',
    'pollen.addAllergyButton': 'Add Allergy',
    'pollen.currentSeason': 'Current Season Pollen',
    'pollen.active': 'active',
    'pollen.yourTracked': 'Your Tracked Allergies',
    'pollen.scale': 'Pollen Scale:',
    'pollen.scaleInfo': '0 = No risk • 1-2 = Low • 3-5 = Medium • 6-8 = High • 9+ = Very High',
    'pollen.alertInfo': 'Red alerts for your tracked allergies when levels may affect you',
    'pollen.adviceInfo': 'Higher numbers indicate increased pollen concentration. Consider limiting outdoor activities during high pollen periods.',
    'pollen.noRisk': 'No risk',
    'pollen.medium': 'Medium',
    'pollen.earlySpring': 'Early Spring',
    'pollen.spring': 'Spring',
    'pollen.lateSpring': 'Late Spring/Summer',
    'pollen.lateSummer': 'Late Summer',
    'pollen.springSummer': 'Spring/Summer',
    'pollen.autumn': 'Fall',
    'pollen.alreadyTracked': 'You already have this allergy tracked',
    'pollen.addFailed': 'Failed to add allergy',
    'pollen.addSuccess': 'Allergy added successfully',
    'pollen.removeFailed': 'Failed to remove allergy',
    'pollen.removeSuccess': 'Allergy removed',
    
    // Footer
    'footer.dataFrom': 'Data from',
    'footer.disclaimer': 'We are not to be held accountable for any inaccuracies or wrong claims.',
    'footer.about': 'About',
    'footer.blog': 'Blog',
    'footer.download': 'Download',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.dataPrivacy': 'Data & Privacy Settings',
    'footer.copyright': '© 2025-{year} Rainz. All rights reserved.',
    'card.tenDay': '10-Day Forecast',
    'card.hourly': '24-Hour Forecast',
    'card.hourlyTap': 'Tap any hour for details',
    'card.showLess': 'Show Less',
    'card.showAll': 'Show All 10 Days',
    'card.hourlyBreakdown': 'Hourly Breakdown',
    'card.weatherMap': 'Weather Map',
    'card.airQuality': 'Air Quality Index',
    'card.sunMoon': 'Sun & Moon',
    'card.uvIndex': 'UV Index',
    'card.sunrise': 'Sunrise',
    'card.sunset': 'Sunset',
    'card.daylight': 'Daylight',
    'card.moonRise': 'Rise',
    'card.moonSet': 'Set',
    'card.moonPhase': 'Phase',
    'card.precipitation': 'Precipitation',
    'card.opacity': 'Opacity',
    'card.past': 'Past',
    'card.forecast': 'Forecast',
    'card.tempHeatmap': 'Temperature Heatmap',
    'card.windLayer': 'Wind Speed Layer',
    'streak.day': 'day',
    'streak.days': 'days',
    'streak.current': 'Current streak',
    'streak.best': 'best',
    'streak.visit': 'visit',
    'streak.visits': 'visits',
    'uv.low': 'Low - No protection needed',
    'uv.moderate': 'Moderate - Some protection needed',
    'uv.high': 'High - Wear sunscreen',
    'uv.veryHigh': 'Very High - Extra protection needed',
    'uv.extreme': 'Extreme - Avoid sun exposure',
    
    // Languages
    'language.en-GB': 'British English',
    'language.en-US': 'American English',
    'language.da': 'Dansk',
    'language.sv': 'Svenska',
    'language.no': 'Norsk',
    'language.fr': 'Français',
    'language.it': 'Italiano',
    'language.boomer': '👴 Boomer',
  },
  'da': {
    // Header
    'app.tagline': 'Sigter mod at være den bedste vejr-app.',
    'header.signIn': 'Log Ind',
    'search.placeholder': 'Søg efter en placering...',
    'search.searching': 'Søger...',
    'search.noResults': 'Ingen placeringer fundet',
    
    // Weather
    'weather.welcome': 'Velkommen til Rainz',
    'weather.searchLocation': 'Søg efter en placering ovenfor eller tillad adgang til placering',
    'weather.failed': 'Kunne ikke indlæse vejrdata',
    'weather.tryAgain': 'Prøv Igen',
    'weather.demoData': 'Demo Data',
    'weather.demoMessage': 'API-nøgler nødvendige for reelle data',
    'weather.refresh': 'Opdater',
    'weather.locationCard': 'Placeringskort',
    'weather.myLocation': 'Min Placering',
    'weather.checkConnection': 'Tjek venligst din forbindelse og prøv igen',
    
    // Weather metrics
    'weather.wind': 'Vind',
    'weather.visibility': 'Sigtbarhed',
    'weather.feelsLike': 'Føles som',
    'weather.humidity': 'Luftfugtighed',
    'weather.pressure': 'Tryk',
    'weather.uvIndex': 'UV-indeks',
    
    // Time
    'time.goodMorning': 'God Morgen!',
    'time.dismiss': 'Afvis',
    'time.today': 'I dag',
    'time.tomorrow': 'I morgen',
    
    // Morning Review
    'morning.title': 'AI Morgen Gennemgang',
    'morning.generating': 'Genererer din morgen briefing...',
    'morning.generate': 'Generer AI Morgen Briefing',
    'morning.outfit': 'Hvad skal man have på:',
    'morning.pollenAlerts': 'Pollen Advarsler',
    'morning.activities': 'Aktiviteter:',
    'morning.keyInsight': 'Vigtig Indsigt:',
    
    // Settings
    'settings.title': 'Indstillinger',
    'settings.account': 'Konto',
    'settings.appearance': 'Udseende',
    'settings.notifications': 'Notifikationer',
    'settings.language': 'Sprog',
    'settings.signOut': 'Log Ud',
    'settings.enableNotifications': 'Aktivér Notifikationer',
    'settings.testNotification': 'Send Test Notifikation',
    'settings.cardVisibility': 'Kort Synlighed',
    'settings.cardOrder': 'Kort Rækkefølge',
    'settings.save': 'Gem',
    'settings.customise': 'Tilpas din vejr-app oplevelse',
    'settings.temperatureUnits': 'Temperaturenheder',
    'settings.useCelsius': 'Brug Celsius (°C)',
    'settings.currentlyFahrenheit': 'Bruger i øjeblikket Fahrenheit (°F)',
    'settings.currentlyCelsius': 'Bruger i øjeblikket Celsius (°C)',
    'settings.reset': 'Nulstil',
    'settings.reloadChanges': 'Genindlæs for at aktivere ændringer.',
    'settings.languageChanged': 'Sprog ændret',
    'settings.changedTo': 'Ændret til',
    
    // Pollen
    'pollen.title': 'Pollenprognose',
    'pollen.track': 'Spor Allergier',
    'pollen.low': 'Lav',
    'pollen.moderate': 'Moderat',
    'pollen.high': 'Høj',
    'pollen.veryHigh': 'Meget Høj',
    'pollen.pollenIndex': 'Pollenindeks',
    'pollen.hourlyForecast': '24-Timers Prognose',
    'pollen.tenDayForecast': '10-Dages Prognose',
    'pollen.detailedMetrics': 'Detaljerede Målinger',
    'pollen.userRoutines': 'Brugerrutiner',
    'pollen.liveData': 'Live sæsonbestemte allergidata',
    'pollen.noData': 'Ingen pollendata tilgængelige',
    'pollen.locationRequired': 'Placeringsdata påkrævet',
    'pollen.trackAllergy': 'Spor Allergi',
    'pollen.addAllergy': 'Tilføj Allergi at Spore',
    'pollen.allergen': 'Allergen',
    'pollen.allergenPlaceholder': 'f.eks. Græs, Birk, Ambrosie',
    'pollen.sensitivityLevel': 'Følsomhedsniveau',
    'pollen.mild': 'Mild',
    'pollen.severe': 'Alvorlig',
    'pollen.addAllergyButton': 'Tilføj Allergi',
    'pollen.currentSeason': 'Nuværende Sæson Pollen',
    'pollen.active': 'aktiv',
    'pollen.yourTracked': 'Dine Sporede Allergier',
    'pollen.scale': 'Pollenskala:',
    'pollen.scaleInfo': '0 = Ingen risiko • 1-2 = Lav • 3-5 = Medium • 6-8 = Høj • 9+ = Meget Høj',
    'pollen.alertInfo': 'Røde advarsler for dine sporede allergier, når niveauerne kan påvirke dig',
    'pollen.adviceInfo': 'Højere tal indikerer øget pollenkoncentration. Overvej at begrænse udendørs aktiviteter i perioder med højt pollental.',
    'pollen.noRisk': 'Ingen risiko',
    'pollen.medium': 'Medium',
    'pollen.earlySpring': 'Tidligt Forår',
    'pollen.spring': 'Forår',
    'pollen.lateSpring': 'Sent Forår/Sommer',
    'pollen.lateSummer': 'Sen Sommer',
    'pollen.springSummer': 'Forår/Sommer',
    'pollen.autumn': 'Efterår',
    'pollen.alreadyTracked': 'Du har allerede denne allergi sporet',
    'pollen.addFailed': 'Kunne ikke tilføje allergi',
    'pollen.addSuccess': 'Allergi tilføjet med succes',
    'pollen.removeFailed': 'Kunne ikke fjerne allergi',
    'pollen.removeSuccess': 'Allergi fjernet',
    
    // Footer
    'footer.dataFrom': 'Data fra',
    'footer.disclaimer': 'Vi er ikke ansvarlige for unøjagtigheder eller forkerte påstande.',
    'footer.about': 'Om',
    'footer.blog': 'Blog',
    'footer.download': 'Download',
    'footer.privacy': 'Privatlivspolitik',
    'footer.terms': 'Servicevilkår',
    'footer.dataPrivacy': 'Data & Privatlivsindstillinger',
    'footer.copyright': '© 2025-{year} Rainz. Alle rettigheder forbeholdes.',
    'card.tenDay': '10-Dages Prognose',
    'card.hourly': '24-Timers Prognose',
    'card.hourlyTap': 'Tryk på en time for detaljer',
    'card.showLess': 'Vis Mindre',
    'card.showAll': 'Vis Alle 10 Dage',
    'card.hourlyBreakdown': 'Timevis Opdeling',
    'card.weatherMap': 'Vejrkort',
    'card.airQuality': 'Luftkvalitetsindeks',
    'card.sunMoon': 'Sol & Måne',
    'card.uvIndex': 'UV-indeks',
    'card.sunrise': 'Solopgang',
    'card.sunset': 'Solnedgang',
    'card.daylight': 'Dagslys',
    'card.moonRise': 'Opgang',
    'card.moonSet': 'Nedgang',
    'card.moonPhase': 'Fase',
    'card.precipitation': 'Nedbør',
    'card.opacity': 'Gennemsigtighed',
    'card.past': 'Fortid',
    'card.forecast': 'Prognose',
    'card.tempHeatmap': 'Temperatur Varmekort',
    'card.windLayer': 'Vindhastighed Lag',
    'streak.day': 'dag',
    'streak.days': 'dage',
    'streak.current': 'Nuværende streak',
    'streak.best': 'bedst',
    'streak.visit': 'besøg',
    'streak.visits': 'besøg',
    'uv.low': 'Lav - Ingen beskyttelse nødvendig',
    'uv.moderate': 'Moderat - Noget beskyttelse nødvendig',
    'uv.high': 'Høj - Brug solcreme',
    'uv.veryHigh': 'Meget Høj - Ekstra beskyttelse nødvendig',
    'uv.extreme': 'Ekstrem - Undgå soleksponering',
    
    // Languages
    'language.en-GB': 'British English',
    'language.en-US': 'American English',
    'language.da': 'Dansk',
    'language.sv': 'Svenska',
    'language.no': 'Norsk',
    'language.fr': 'Français',
    'language.it': 'Italiano',
    'language.boomer': '👴 Boomer',
  },
  'sv': {
    // Header
    'app.tagline': 'Strävar efter att vara den bästa väderappen.',
    'header.signIn': 'Logga In',
    'search.placeholder': 'Sök efter en plats...',
    'search.searching': 'Söker...',
    'search.noResults': 'Inga platser hittades',
    
    // Weather
    'weather.welcome': 'Välkommen till Rainz',
    'weather.searchLocation': 'Sök efter en plats ovan eller tillåt platstillgång',
    'weather.failed': 'Kunde inte ladda väderdata',
    'weather.tryAgain': 'Försök Igen',
    'weather.demoData': 'Demo Data',
    'weather.demoMessage': 'API-nycklar behövs för riktig data',
    'weather.refresh': 'Uppdatera',
    'weather.locationCard': 'Platskort',
    'weather.myLocation': 'Min Plats',
    'weather.checkConnection': 'Vänligen kontrollera din anslutning och försök igen',
    
    // Weather metrics
    'weather.wind': 'Vind',
    'weather.visibility': 'Sikt',
    'weather.feelsLike': 'Känns som',
    'weather.humidity': 'Luftfuktighet',
    'weather.pressure': 'Tryck',
    'weather.uvIndex': 'UV-index',
    
    // Time
    'time.goodMorning': 'God Morgon!',
    'time.dismiss': 'Avfärda',
    'time.today': 'Idag',
    'time.tomorrow': 'Imorgon',
    
    // Morning Review
    'morning.title': 'AI Morgon Översikt',
    'morning.generating': 'Genererar din morgonbriefing...',
    'morning.generate': 'Generera AI Morgonbriefing',
    'morning.outfit': 'Vad ska man ha på sig:',
    'morning.pollenAlerts': 'Pollenvarningar',
    'morning.activities': 'Aktiviteter:',
    'morning.keyInsight': 'Viktig Insikt:',
    
    // Settings
    'settings.title': 'Inställningar',
    'settings.account': 'Konto',
    'settings.appearance': 'Utseende',
    'settings.notifications': 'Notifikationer',
    'settings.language': 'Språk',
    'settings.signOut': 'Logga Ut',
    'settings.enableNotifications': 'Aktivera Notifikationer',
    'settings.testNotification': 'Skicka Test Notifikation',
    'settings.cardVisibility': 'Kort Synlighet',
    'settings.cardOrder': 'Kort Ordning',
    'settings.save': 'Spara',
    'settings.customise': 'Anpassa din väderapp-upplevelse',
    'settings.temperatureUnits': 'Temperaturenheter',
    'settings.useCelsius': 'Använd Celsius (°C)',
    'settings.currentlyFahrenheit': 'Använder för närvarande Fahrenheit (°F)',
    'settings.currentlyCelsius': 'Använder för närvarande Celsius (°C)',
    'settings.reset': 'Återställ',
    'settings.reloadChanges': 'Ladda om för att aktivera ändringar.',
    'settings.languageChanged': 'Språk ändrat',
    'settings.changedTo': 'Ändrat till',
    
    // Pollen
    'pollen.title': 'Pollenprognos',
    'pollen.track': 'Spåra Allergier',
    'pollen.low': 'Låg',
    'pollen.moderate': 'Måttlig',
    'pollen.high': 'Hög',
    'pollen.veryHigh': 'Mycket Hög',
    'pollen.pollenIndex': 'Pollenindex',
    'pollen.hourlyForecast': '24-Timmars Prognos',
    'pollen.tenDayForecast': '10-Dagars Prognos',
    'pollen.detailedMetrics': 'Detaljerade Mätningar',
    'pollen.userRoutines': 'Användarrutiner',
    'pollen.liveData': 'Live säsongsallergidata',
    'pollen.noData': 'Ingen pollendata tillgänglig',
    'pollen.locationRequired': 'Platsdata krävs',
    'pollen.trackAllergy': 'Spåra Allergi',
    'pollen.addAllergy': 'Lägg till Allergi att Spåra',
    'pollen.allergen': 'Allergen',
    'pollen.allergenPlaceholder': 't.ex. Gräs, Björk, Ragweed',
    'pollen.sensitivityLevel': 'Känslighetsnivå',
    'pollen.mild': 'Mild',
    'pollen.severe': 'Allvarlig',
    'pollen.addAllergyButton': 'Lägg till Allergi',
    'pollen.currentSeason': 'Nuvarande Säsongs Pollen',
    'pollen.active': 'aktiv',
    'pollen.yourTracked': 'Dina Spårade Allergier',
    'pollen.scale': 'Pollenskala:',
    'pollen.scaleInfo': '0 = Ingen risk • 1-2 = Låg • 3-5 = Medium • 6-8 = Hög • 9+ = Mycket Hög',
    'pollen.alertInfo': 'Röda larm för dina spårade allergier när nivåerna kan påverka dig',
    'pollen.adviceInfo': 'Högre siffror indikerar ökad pollenkoncentration. Överväg att begränsa utomhusaktiviteter under perioder med högt pollen.',
    'pollen.noRisk': 'Ingen risk',
    'pollen.medium': 'Medium',
    'pollen.earlySpring': 'Tidig Vår',
    'pollen.spring': 'Vår',
    'pollen.lateSpring': 'Sen Vår/Sommar',
    'pollen.lateSummer': 'Sen Sommar',
    'pollen.springSummer': 'Vår/Sommar',
    'pollen.autumn': 'Höst',
    'pollen.alreadyTracked': 'Du har redan denna allergi spårad',
    'pollen.addFailed': 'Kunde inte lägga till allergi',
    'pollen.addSuccess': 'Allergi tillagd framgångsrikt',
    'pollen.removeFailed': 'Kunde inte ta bort allergi',
    'pollen.removeSuccess': 'Allergi borttagen',
    
    // Footer
    'footer.dataFrom': 'Data från',
    'footer.disclaimer': 'Vi ansvarar inte för felaktigheter eller felaktiga påståenden.',
    'footer.about': 'Om',
    'footer.blog': 'Blogg',
    'footer.download': 'Ladda ner',
    'footer.privacy': 'Integritetspolicy',
    'footer.terms': 'Användarvillkor',
    'footer.dataPrivacy': 'Data & Integritetsinställningar',
    'footer.copyright': '© 2025-{year} Rainz. Alla rättigheter förbehållna.',
    'card.tenDay': '10-Dagars Prognos',
    'card.hourly': '24-Timmars Prognos',
    'card.hourlyTap': 'Tryck på en timme för detaljer',
    'card.showLess': 'Visa Mindre',
    'card.showAll': 'Visa Alla 10 Dagar',
    'card.hourlyBreakdown': 'Timvis Uppdelning',
    'card.weatherMap': 'Väderkarta',
    'card.airQuality': 'Luftkvalitetsindex',
    'card.sunMoon': 'Sol & Måne',
    'card.uvIndex': 'UV-index',
    'card.sunrise': 'Soluppgång',
    'card.sunset': 'Solnedgång',
    'card.daylight': 'Dagsljus',
    'card.moonRise': 'Uppgång',
    'card.moonSet': 'Nedgång',
    'card.moonPhase': 'Fas',
    'card.precipitation': 'Nederbörd',
    'card.opacity': 'Opacitet',
    'card.past': 'Förfluten',
    'card.forecast': 'Prognos',
    'card.tempHeatmap': 'Temperatur Värmekarta',
    'card.windLayer': 'Vindhastighet Lager',
    'streak.day': 'dag',
    'streak.days': 'dagar',
    'streak.current': 'Nuvarande streak',
    'streak.best': 'bäst',
    'streak.visit': 'besök',
    'streak.visits': 'besök',
    'uv.low': 'Låg - Inget skydd behövs',
    'uv.moderate': 'Måttlig - Visst skydd behövs',
    'uv.high': 'Hög - Använd solskydd',
    'uv.veryHigh': 'Mycket Hög - Extra skydd behövs',
    'uv.extreme': 'Extrem - Undvik solexponering',
    'language.en-GB': 'British English',
    'language.en-US': 'American English',
    'language.da': 'Dansk',
    'language.sv': 'Svenska',
    'language.no': 'Norsk',
    'language.fr': 'Français',
    'language.it': 'Italiano',
    'language.boomer': '👴 Boomer',
  },
  'no': {
    // Header
    'app.tagline': 'Sikter på å være den beste værappen.',
    'header.signIn': 'Logg Inn',
    'search.placeholder': 'Søk etter en plassering...',
    'search.searching': 'Søker...',
    'search.noResults': 'Ingen plasseringer funnet',
    
    // Weather
    'weather.welcome': 'Velkommen til Rainz',
    'weather.searchLocation': 'Søk etter en plassering ovenfor eller tillat plasseringstilgang',
    'weather.failed': 'Kunne ikke laste værdata',
    'weather.tryAgain': 'Prøv Igjen',
    'weather.demoData': 'Demo Data',
    'weather.demoMessage': 'API-nøkler nødvendig for ekte data',
    'weather.refresh': 'Oppdater',
    'weather.locationCard': 'Plasseringskort',
    'weather.myLocation': 'Min Plassering',
    'weather.checkConnection': 'Vennligst sjekk tilkoblingen din og prøv igjen',
    
    // Weather metrics
    'weather.wind': 'Vind',
    'weather.visibility': 'Sikt',
    'weather.feelsLike': 'Føles som',
    'weather.humidity': 'Luftfuktighet',
    'weather.pressure': 'Trykk',
    'weather.uvIndex': 'UV-indeks',
    
    // Time
    'time.goodMorning': 'God Morgen!',
    'time.dismiss': 'Avvis',
    'time.today': 'I dag',
    'time.tomorrow': 'I morgen',
    
    // Morning Review
    'morning.title': 'AI Morgen Oversikt',
    'morning.generating': 'Genererer din morgenbriefing...',
    'morning.generate': 'Generer AI Morgenbriefing',
    'morning.outfit': 'Hva skal man ha på seg:',
    'morning.pollenAlerts': 'Pollenvarsler',
    'morning.activities': 'Aktiviteter:',
    'morning.keyInsight': 'Viktig Innsikt:',
    
    // Settings
    'settings.title': 'Innstillinger',
    'settings.account': 'Konto',
    'settings.appearance': 'Utseende',
    'settings.notifications': 'Varsler',
    'settings.language': 'Språk',
    'settings.signOut': 'Logg Ut',
    'settings.enableNotifications': 'Aktiver Varsler',
    'settings.testNotification': 'Send Test Varsel',
    'settings.cardVisibility': 'Kort Synlighet',
    'settings.cardOrder': 'Kort Rekkefølge',
    'settings.save': 'Lagre',
    'settings.customise': 'Tilpass værrapp-opplevelsen din',
    'settings.temperatureUnits': 'Temperaturenheter',
    'settings.useCelsius': 'Bruk Celsius (°C)',
    'settings.currentlyFahrenheit': 'Bruker for øyeblikket Fahrenheit (°F)',
    'settings.currentlyCelsius': 'Bruker for øyeblikket Celsius (°C)',
    'settings.reset': 'Tilbakestill',
    'settings.reloadChanges': 'Last inn på nytt for å aktivere endringer.',
    'settings.languageChanged': 'Språk endret',
    'settings.changedTo': 'Endret til',
    
    // Pollen
    'pollen.title': 'Pollenvarsel',
    'pollen.track': 'Spor Allergier',
    'pollen.low': 'Lav',
    'pollen.moderate': 'Moderat',
    'pollen.high': 'Høy',
    'pollen.veryHigh': 'Veldig Høy',
    'pollen.pollenIndex': 'Pollenindeks',
    'pollen.hourlyForecast': '24-Timers Varsel',
    'pollen.tenDayForecast': '10-Dagers Varsel',
    'pollen.detailedMetrics': 'Detaljerte Målinger',
    'pollen.userRoutines': 'Brukerrutiner',
    'pollen.liveData': 'Live sesongallergidata',
    'pollen.noData': 'Ingen pollendata tilgjengelig',
    'pollen.locationRequired': 'Plasseringsdata kreves',
    'pollen.trackAllergy': 'Spor Allergi',
    'pollen.addAllergy': 'Legg til Allergi å Spore',
    'pollen.allergen': 'Allergen',
    'pollen.allergenPlaceholder': 'f.eks. Gress, Bjørk, Ragweed',
    'pollen.sensitivityLevel': 'Følsomhetsnivå',
    'pollen.mild': 'Mild',
    'pollen.severe': 'Alvorlig',
    'pollen.addAllergyButton': 'Legg til Allergi',
    'pollen.currentSeason': 'Nåværende Sesong Pollen',
    'pollen.active': 'aktiv',
    'pollen.yourTracked': 'Dine Sporede Allergier',
    'pollen.scale': 'Pollenskala:',
    'pollen.scaleInfo': '0 = Ingen risiko • 1-2 = Lav • 3-5 = Medium • 6-8 = Høy • 9+ = Veldig Høy',
    'pollen.alertInfo': 'Røde varsler for dine sporede allergier når nivåene kan påvirke deg',
    'pollen.adviceInfo': 'Høyere tall indikerer økt pollenkonsentrasjon. Vurder å begrense utendørs aktiviteter i perioder med høyt pollen.',
    'pollen.noRisk': 'Ingen risiko',
    'pollen.medium': 'Medium',
    'pollen.earlySpring': 'Tidlig Vår',
    'pollen.spring': 'Vår',
    'pollen.lateSpring': 'Sen Vår/Sommer',
    'pollen.lateSummer': 'Sen Sommer',
    'pollen.springSummer': 'Vår/Sommer',
    'pollen.autumn': 'Høst',
    'pollen.alreadyTracked': 'Du har allerede denne allergien sporet',
    'pollen.addFailed': 'Kunne ikke legge til allergi',
    'pollen.addSuccess': 'Allergi lagt til vellykket',
    'pollen.removeFailed': 'Kunne ikke fjerne allergi',
    'pollen.removeSuccess': 'Allergi fjernet',
    
    // Footer & Cards
    'footer.dataFrom': 'Data fra',
    'footer.disclaimer': 'Vi er ikke ansvarlige for unøyaktigheter eller feil påstander.',
    'footer.about': 'Om',
    'footer.blog': 'Blogg',
    'footer.download': 'Last ned',
    'footer.privacy': 'Personvernerklæring',
    'footer.terms': 'Tjenestevilkår',
    'footer.dataPrivacy': 'Data & Personverninnstillinger',
    'footer.copyright': '© 2025-{year} Rainz. Alle rettigheter forbeholdt.',
    'card.tenDay': '10-Dagers Varsel',
    'card.hourly': '24-Timers Varsel',
    'card.hourlyTap': 'Trykk på en time for detaljer',
    'card.showLess': 'Vis Mindre',
    'card.showAll': 'Vis Alle 10 Dager',
    'card.hourlyBreakdown': 'Timevis Oversikt',
    'card.weatherMap': 'Værkart',
    'card.airQuality': 'Luftkvalitetsindeks',
    'card.sunMoon': 'Sol & Måne',
    'card.uvIndex': 'UV-indeks',
    'card.sunrise': 'Soloppgang',
    'card.sunset': 'Solnedgang',
    'card.daylight': 'Dagslys',
    'card.moonRise': 'Oppgang',
    'card.moonSet': 'Nedgang',
    'card.moonPhase': 'Fase',
    'card.precipitation': 'Nedbør',
    'card.opacity': 'Gjennomsiktighet',
    'card.past': 'Fortid',
    'card.forecast': 'Varsel',
    'card.tempHeatmap': 'Temperatur Varmekart',
    'card.windLayer': 'Vindhastighet Lag',
    'streak.day': 'dag',
    'streak.days': 'dager',
    'streak.current': 'Nåværende streak',
    'streak.best': 'best',
    'streak.visit': 'besøk',
    'streak.visits': 'besøk',
    'uv.low': 'Lav - Ingen beskyttelse nødvendig',
    'uv.moderate': 'Moderat - Noe beskyttelse nødvendig',
    'uv.high': 'Høy - Bruk solkrem',
    'uv.veryHigh': 'Veldig Høy - Ekstra beskyttelse nødvendig',
    'uv.extreme': 'Ekstrem - Unngå soleksponering',
    'language.en-GB': 'British English',
    'language.en-US': 'American English',
    'language.da': 'Dansk',
    'language.sv': 'Svenska',
    'language.no': 'Norsk',
    'language.fr': 'Français',
    'language.it': 'Italiano',
    'language.boomer': '👴 Boomer',
  },
  'fr': {
    // Header
    'app.tagline': 'Visant à être la meilleure application météo.',
    'header.signIn': 'Se Connecter',
    'search.placeholder': 'Rechercher un lieu...',
    'search.searching': 'Recherche en cours...',
    'search.noResults': 'Aucun lieu trouvé',
    
    // Weather
    'weather.welcome': 'Bienvenue sur Rainz',
    'weather.searchLocation': 'Recherchez un lieu ci-dessus ou autorisez l\'accès à la localisation',
    'weather.failed': 'Échec du chargement des données météo',
    'weather.tryAgain': 'Réessayer',
    'weather.demoData': 'Données de Démonstration',
    'weather.demoMessage': 'Clés API nécessaires pour les données réelles',
    'weather.refresh': 'Actualiser',
    'weather.locationCard': 'Carte de Localisation',
    'weather.myLocation': 'Ma Position',
    'weather.checkConnection': 'Veuillez vérifier votre connexion et réessayer',
    
    // Weather metrics
    'weather.wind': 'Vent',
    'weather.visibility': 'Visibilité',
    'weather.feelsLike': 'Ressenti',
    'weather.humidity': 'Humidité',
    'weather.pressure': 'Pression',
    'weather.uvIndex': 'Indice UV',
    
    // Time
    'time.goodMorning': 'Bonjour!',
    'time.dismiss': 'Rejeter',
    'time.today': 'Aujourd\'hui',
    'time.tomorrow': 'Demain',
    
    // Morning Review
    'morning.title': 'Revue Matinale IA',
    'morning.generating': 'Génération de votre briefing matinal...',
    'morning.generate': 'Générer Briefing Matinal IA',
    'morning.outfit': 'Quoi Porter:',
    'morning.pollenAlerts': 'Alertes Pollen',
    'morning.activities': 'Activités:',
    'morning.keyInsight': 'Conseil Clé:',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.account': 'Compte',
    'settings.appearance': 'Apparence',
    'settings.notifications': 'Notifications',
    'settings.language': 'Langue',
    'settings.signOut': 'Se Déconnecter',
    'settings.enableNotifications': 'Activer les Notifications',
    'settings.testNotification': 'Envoyer une Notification de Test',
    'settings.cardVisibility': 'Visibilité des Cartes',
    'settings.cardOrder': 'Ordre des Cartes',
    'settings.save': 'Enregistrer',
    'settings.customise': 'Personnalisez votre expérience météo',
    'settings.temperatureUnits': 'Unités de Température',
    'settings.useCelsius': 'Utiliser Celsius (°C)',
    'settings.currentlyFahrenheit': 'Utilise actuellement Fahrenheit (°F)',
    'settings.currentlyCelsius': 'Utilise actuellement Celsius (°C)',
    'settings.reset': 'Réinitialiser',
    'settings.reloadChanges': 'Rechargez pour activer les modifications.',
    'settings.languageChanged': 'Langue modifiée',
    'settings.changedTo': 'Changé en',
    
    // Pollen
    'pollen.title': 'Prévisions Polliniques',
    'pollen.track': 'Suivre les Allergies',
    'pollen.low': 'Faible',
    'pollen.moderate': 'Modéré',
    'pollen.high': 'Élevé',
    'pollen.veryHigh': 'Très Élevé',
    'pollen.pollenIndex': 'Indice Pollinique',
    'pollen.hourlyForecast': 'Prévisions sur 24 Heures',
    'pollen.tenDayForecast': 'Prévisions sur 10 Jours',
    'pollen.detailedMetrics': 'Métriques Détaillées',
    'pollen.userRoutines': 'Routines Utilisateur',
    'pollen.liveData': 'Données d\'allergies saisonnières en direct',
    'pollen.noData': 'Aucune donnée pollinique disponible',
    'pollen.locationRequired': 'Données de localisation requises',
    'pollen.trackAllergy': 'Suivre Allergie',
    'pollen.addAllergy': 'Ajouter Allergie à Suivre',
    'pollen.allergen': 'Allergène',
    'pollen.allergenPlaceholder': 'p.ex. Herbe, Bouleau, Ambroisie',
    'pollen.sensitivityLevel': 'Niveau de Sensibilité',
    'pollen.mild': 'Léger',
    'pollen.severe': 'Grave',
    'pollen.addAllergyButton': 'Ajouter Allergie',
    'pollen.currentSeason': 'Pollen de Saison Actuelle',
    'pollen.active': 'actif',
    'pollen.yourTracked': 'Vos Allergies Suivies',
    'pollen.scale': 'Échelle Pollinique :',
    'pollen.scaleInfo': '0 = Aucun risque • 1-2 = Faible • 3-5 = Moyen • 6-8 = Élevé • 9+ = Très Élevé',
    'pollen.alertInfo': 'Alertes rouges pour vos allergies suivies lorsque les niveaux peuvent vous affecter',
    'pollen.adviceInfo': 'Des nombres plus élevés indiquent une concentration de pollen accrue. Envisagez de limiter les activités extérieures pendant les périodes de pollen élevé.',
    'pollen.noRisk': 'Aucun risque',
    'pollen.medium': 'Moyen',
    'pollen.earlySpring': 'Début du Printemps',
    'pollen.spring': 'Printemps',
    'pollen.lateSpring': 'Fin du Printemps/Été',
    'pollen.lateSummer': 'Fin de l\'Été',
    'pollen.springSummer': 'Printemps/Été',
    'pollen.autumn': 'Automne',
    'pollen.alreadyTracked': 'Vous suivez déjà cette allergie',
    'pollen.addFailed': 'Échec de l\'ajout de l\'allergie',
    'pollen.addSuccess': 'Allergie ajoutée avec succès',
    'pollen.removeFailed': 'Échec de la suppression de l\'allergie',
    'pollen.removeSuccess': 'Allergie supprimée',
    
    // Footer & Cards
    'footer.dataFrom': 'Données de',
    'footer.disclaimer': 'Nous ne sommes pas responsables des inexactitudes ou des fausses déclarations.',
    'footer.about': 'À propos',
    'footer.blog': 'Blog',
    'footer.download': 'Télécharger',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.dataPrivacy': 'Données & Paramètres de confidentialité',
    'footer.copyright': '© 2025-{year} Rainz. Tous droits réservés.',
    'card.tenDay': 'Prévisions 10 Jours',
    'card.hourly': 'Prévisions 24 Heures',
    'card.hourlyTap': 'Appuyez sur une heure pour les détails',
    'card.showLess': 'Voir Moins',
    'card.showAll': 'Voir Les 10 Jours',
    'card.hourlyBreakdown': 'Détail Horaire',
    'card.weatherMap': 'Carte Météo',
    'card.airQuality': 'Indice de Qualité de l\'Air',
    'card.sunMoon': 'Soleil & Lune',
    'card.uvIndex': 'Indice UV',
    'card.sunrise': 'Lever du soleil',
    'card.sunset': 'Coucher du soleil',
    'card.daylight': 'Lumière du jour',
    'card.moonRise': 'Lever',
    'card.moonSet': 'Coucher',
    'card.moonPhase': 'Phase',
    'card.precipitation': 'Précipitations',
    'card.opacity': 'Opacité',
    'card.past': 'Passé',
    'card.forecast': 'Prévision',
    'card.tempHeatmap': 'Carte Thermique',
    'card.windLayer': 'Couche de Vent',
    'streak.day': 'jour',
    'streak.days': 'jours',
    'streak.current': 'Série actuelle',
    'streak.best': 'meilleur',
    'streak.visit': 'visite',
    'streak.visits': 'visites',
    'uv.low': 'Faible - Aucune protection nécessaire',
    'uv.moderate': 'Modéré - Un peu de protection nécessaire',
    'uv.high': 'Élevé - Portez de la crème solaire',
    'uv.veryHigh': 'Très Élevé - Protection supplémentaire nécessaire',
    'uv.extreme': 'Extrême - Évitez l\'exposition au soleil',
    'language.en-GB': 'British English',
    'language.en-US': 'American English',
    'language.da': 'Dansk',
    'language.sv': 'Svenska',
    'language.no': 'Norsk',
    'language.fr': 'Français',
    'language.it': 'Italiano',
    'language.boomer': '👴 Boomer',
  },
  'it': {
    // Header
    'app.tagline': 'Mira ad essere la migliore app meteo.',
    'header.signIn': 'Accedi',
    'search.placeholder': 'Cerca una località...',
    'search.searching': 'Ricerca in corso...',
    'search.noResults': 'Nessuna località trovata',
    
    // Weather
    'weather.welcome': 'Benvenuto su Rainz',
    'weather.searchLocation': 'Cerca una località sopra o consenti l\'accesso alla posizione',
    'weather.failed': 'Impossibile caricare i dati meteo',
    'weather.tryAgain': 'Riprova',
    'weather.demoData': 'Dati Demo',
    'weather.demoMessage': 'Chiavi API necessarie per dati reali',
    'weather.refresh': 'Aggiorna',
    'weather.locationCard': 'Scheda Località',
    'weather.myLocation': 'La Mia Posizione',
    'weather.checkConnection': 'Controlla la tua connessione e riprova',
    
    // Weather metrics
    'weather.wind': 'Vento',
    'weather.visibility': 'Visibilità',
    'weather.feelsLike': 'Percepita',
    'weather.humidity': 'Umidità',
    'weather.pressure': 'Pressione',
    'weather.uvIndex': 'Indice UV',
    
    // Time
    'time.goodMorning': 'Buongiorno!',
    'time.dismiss': 'Ignora',
    'time.today': 'Oggi',
    'time.tomorrow': 'Domani',
    
    // Morning Review
    'morning.title': 'Revisione Mattutina IA',
    'morning.generating': 'Generazione del tuo briefing mattutino...',
    'morning.generate': 'Genera Briefing Mattutino IA',
    'morning.outfit': 'Cosa Indossare:',
    'morning.pollenAlerts': 'Avvisi Polline',
    'morning.activities': 'Attività:',
    'morning.keyInsight': 'Consiglio Chiave:',
    
    // Settings
    'settings.title': 'Impostazioni',
    'settings.account': 'Account',
    'settings.appearance': 'Aspetto',
    'settings.notifications': 'Notifiche',
    'settings.language': 'Lingua',
    'settings.signOut': 'Disconnetti',
    'settings.enableNotifications': 'Attiva Notifiche',
    'settings.testNotification': 'Invia Notifica di Test',
    'settings.cardVisibility': 'Visibilità Schede',
    'settings.cardOrder': 'Ordine Schede',
    'settings.save': 'Salva',
    'settings.customise': 'Personalizza la tua esperienza meteo',
    'settings.temperatureUnits': 'Unità di Temperatura',
    'settings.useCelsius': 'Usa Celsius (°C)',
    'settings.currentlyFahrenheit': 'Attualmente usa Fahrenheit (°F)',
    'settings.currentlyCelsius': 'Attualmente usa Celsius (°C)',
    'settings.reset': 'Ripristina',
    'settings.reloadChanges': 'Ricarica per attivare le modifiche.',
    'settings.languageChanged': 'Lingua cambiata',
    'settings.changedTo': 'Cambiato in',
    
    // Pollen
    'pollen.title': 'Previsioni Polline',
    'pollen.track': 'Traccia Allergie',
    'pollen.low': 'Basso',
    'pollen.moderate': 'Moderato',
    'pollen.high': 'Alto',
    'pollen.veryHigh': 'Molto Alto',
    'pollen.pollenIndex': 'Indice Pollinico',
    'pollen.hourlyForecast': 'Previsioni 24 Ore',
    'pollen.tenDayForecast': 'Previsioni 10 Giorni',
    'pollen.detailedMetrics': 'Metriche Dettagliate',
    'pollen.userRoutines': 'Routine Utente',
    'pollen.liveData': 'Dati allergia stagionale in diretta',
    'pollen.noData': 'Nessun dato pollinico disponibile',
    'pollen.locationRequired': 'Dati di posizione richiesti',
    'pollen.trackAllergy': 'Traccia Allergia',
    'pollen.addAllergy': 'Aggiungi Allergia da Tracciare',
    'pollen.allergen': 'Allergene',
    'pollen.allergenPlaceholder': 'es. Erba, Betulla, Ambrosia',
    'pollen.sensitivityLevel': 'Livello di Sensibilità',
    'pollen.mild': 'Lieve',
    'pollen.severe': 'Grave',
    'pollen.addAllergyButton': 'Aggiungi Allergia',
    'pollen.currentSeason': 'Polline Stagione Corrente',
    'pollen.active': 'attivo',
    'pollen.yourTracked': 'Le Tue Allergie Tracciate',
    'pollen.scale': 'Scala Pollinica:',
    'pollen.scaleInfo': '0 = Nessun rischio • 1-2 = Basso • 3-5 = Medio • 6-8 = Alto • 9+ = Molto Alto',
    'pollen.alertInfo': 'Avvisi rossi per le tue allergie tracciate quando i livelli possono influenzarti',
    'pollen.adviceInfo': 'Numeri più alti indicano una maggiore concentrazione di polline. Considera di limitare le attività all\'aperto durante i periodi di alto polline.',
    'pollen.noRisk': 'Nessun rischio',
    'pollen.medium': 'Medio',
    'pollen.earlySpring': 'Inizio Primavera',
    'pollen.spring': 'Primavera',
    'pollen.lateSpring': 'Fine Primavera/Estate',
    'pollen.lateSummer': 'Fine Estate',
    'pollen.springSummer': 'Primavera/Estate',
    'pollen.autumn': 'Autunno',
    'pollen.alreadyTracked': 'Hai già questa allergia tracciata',
    'pollen.addFailed': 'Impossibile aggiungere allergia',
    'pollen.addSuccess': 'Allergia aggiunta con successo',
    'pollen.removeFailed': 'Impossibile rimuovere allergia',
    'pollen.removeSuccess': 'Allergia rimossa',
    
    // Footer & Cards
    'footer.dataFrom': 'Dati da',
    'footer.disclaimer': 'Non siamo responsabili di inesattezze o affermazioni errate.',
    'footer.about': 'Chi siamo',
    'footer.blog': 'Blog',
    'footer.download': 'Scarica',
    'footer.privacy': 'Politica sulla Privacy',
    'footer.terms': 'Termini di Servizio',
    'footer.dataPrivacy': 'Dati & Impostazioni Privacy',
    'footer.copyright': '© 2025-{year} Rainz. Tutti i diritti riservati.',
    'card.tenDay': 'Previsioni 10 Giorni',
    'card.hourly': 'Previsioni 24 Ore',
    'card.hourlyTap': 'Tocca un\'ora per i dettagli',
    'card.showLess': 'Mostra Meno',
    'card.showAll': 'Mostra Tutti i 10 Giorni',
    'card.hourlyBreakdown': 'Dettaglio Orario',
    'card.weatherMap': 'Mappa Meteo',
    'card.airQuality': 'Indice Qualità dell\'Aria',
    'card.sunMoon': 'Sole & Luna',
    'card.uvIndex': 'Indice UV',
    'card.sunrise': 'Alba',
    'card.sunset': 'Tramonto',
    'card.daylight': 'Luce del giorno',
    'card.moonRise': 'Sorgere',
    'card.moonSet': 'Tramonto',
    'card.moonPhase': 'Fase',
    'card.precipitation': 'Precipitazioni',
    'card.opacity': 'Opacità',
    'card.past': 'Passato',
    'card.forecast': 'Previsione',
    'card.tempHeatmap': 'Mappa Termica',
    'card.windLayer': 'Strato Velocità Vento',
    'streak.day': 'giorno',
    'streak.days': 'giorni',
    'streak.current': 'Serie attuale',
    'streak.best': 'migliore',
    'streak.visit': 'visita',
    'streak.visits': 'visite',
    'uv.low': 'Basso - Nessuna protezione necessaria',
    'uv.moderate': 'Moderato - Un po\' di protezione necessaria',
    'uv.high': 'Alto - Usa la crema solare',
    'uv.veryHigh': 'Molto Alto - Protezione extra necessaria',
    'uv.extreme': 'Estremo - Evita l\'esposizione al sole',
    'language.en-GB': 'British English',
    'language.en-US': 'American English',
    'language.da': 'Dansk',
    'language.sv': 'Svenska',
    'language.no': 'Norsk',
    'language.fr': 'Français',
    'language.it': 'Italiano',
    'language.boomer': '👴 Boomer',
  },
  'boomer': {
    // Header
    'app.tagline': 'It\'s like the weather channel but on your phone thingy.',
    'header.signIn': 'Log Into The Machine',
    'search.placeholder': 'Type a city name here, like Google...',
    'search.searching': 'Hold on, the computer is thinking...',
    'search.noResults': 'The computer can\'t find that place. Did you spell it right?',
    
    // Weather
    'weather.welcome': 'Oh good, you found the weather app!',
    'weather.searchLocation': 'Type something up there or let the phone know where you are (it already knows, trust me)',
    'weather.failed': 'The weather thing is broken. Classic technology.',
    'weather.tryAgain': 'Try Again (Hit This Button)',
    'weather.demoData': 'Fake Weather',
    'weather.demoMessage': 'Need some internet keys for the real stuff',
    'weather.refresh': 'Make It Load Again',
    'weather.locationCard': 'Where You Are Card',
    'weather.myLocation': 'Where I Am Right Now',
    'weather.checkConnection': 'Is the WiFi working? Check that box with the blinking lights.',
    
    // Weather metrics
    'weather.wind': 'How Windy',
    'weather.visibility': 'Can You See Far',
    'weather.feelsLike': 'What it ACTUALLY feels like',
    'weather.humidity': 'The Sticky Air Number',
    'weather.pressure': 'Barometer Thingy',
    'weather.uvIndex': 'Sunburn Risk',
    
    // Time
    'time.goodMorning': 'Rise and Shine, Kiddo!',
    'time.dismiss': 'Make It Go Away',
    'time.today': 'Today',
    'time.tomorrow': 'Tomorrow',
    
    // Morning Review
    'morning.title': 'The Robot Tells You About Today',
    'morning.generating': 'The robot is writing... give it a sec...',
    'morning.generate': 'Ask The Robot About The Weather',
    'morning.outfit': 'What To Wear (Ask Your Mother):',
    'morning.pollenAlerts': 'Sneezy Warnings',
    'morning.activities': 'Things You Can Do Outside:',
    'morning.keyInsight': 'Important Bit:',
    
    // Settings
    'settings.title': 'The Settings (Don\'t Break Anything)',
    'settings.account': 'Your Account',
    'settings.appearance': 'How It Looks',
    'settings.notifications': 'Those Pop-Up Things',
    'settings.language': 'Language',
    'settings.signOut': 'Log Out Of The Machine',
    'settings.enableNotifications': 'Turn On Those Annoying Pop-Ups',
    'settings.testNotification': 'Send A Test Pop-Up',
    'settings.cardVisibility': 'What Boxes To Show',
    'settings.cardOrder': 'What Order The Boxes Go In',
    'settings.save': 'Save (IMPORTANT!)',
    'settings.customise': 'Change stuff around (carefully!)',
    'settings.temperatureUnits': 'Hot/Cold Numbers Style',
    'settings.useCelsius': 'Use Celsius (the normal one)',
    'settings.currentlyFahrenheit': 'Using Fahrenheit (the American one)',
    'settings.currentlyCelsius': 'Using Celsius (the normal one)',
    'settings.reset': 'Put It Back How It Was',
    'settings.reloadChanges': 'Close and open it again to see changes.',
    'settings.languageChanged': 'Language changed!',
    'settings.changedTo': 'Changed to',
    
    // Pollen
    'pollen.title': 'Sneezy Flower Dust Forecast',
    'pollen.track': 'Track Your Sneezes',
    'pollen.low': 'Not Bad',
    'pollen.moderate': 'Bring Tissues',
    'pollen.high': 'Stay Inside',
    'pollen.veryHigh': 'DON\'T GO OUTSIDE',
    'pollen.pollenIndex': 'Sneezy Number',
    'pollen.hourlyForecast': 'Hourly Sneeze Forecast',
    'pollen.tenDayForecast': '10-Day Sneeze Forecast',
    'pollen.detailedMetrics': 'All The Numbers',
    'pollen.userRoutines': 'Your Daily Routines',
    'pollen.liveData': 'Live sneezy data from the internet',
    'pollen.noData': 'No sneeze data. Lucky you!',
    'pollen.locationRequired': 'The phone needs to know where you are first',
    'pollen.trackAllergy': 'Tell Us What Makes You Sneeze',
    'pollen.addAllergy': 'Add Something That Makes You Sneeze',
    'pollen.allergen': 'The Sneezy Thing',
    'pollen.allergenPlaceholder': 'Like Grass, Trees, That Yellow Stuff...',
    'pollen.sensitivityLevel': 'How Bad Is It For You',
    'pollen.mild': 'A Little Sneezy',
    'pollen.severe': 'VERY Sneezy',
    'pollen.addAllergyButton': 'Add It',
    'pollen.currentSeason': 'What\'s Making People Sneeze Now',
    'pollen.active': 'happening now',
    'pollen.yourTracked': 'Your Sneeze Triggers',
    'pollen.scale': 'Sneeze Scale:',
    'pollen.scaleInfo': '0 = Fine • 1-2 = A Bit • 3-5 = Uh Oh • 6-8 = Get The Tissues • 9+ = STAY HOME',
    'pollen.alertInfo': 'We\'ll warn you when the sneezy stuff is bad',
    'pollen.adviceInfo': 'Higher number = more sneezing. Maybe watch TV instead of going to the park.',
    'pollen.noRisk': 'You\'re fine!',
    'pollen.medium': 'Medium',
    'pollen.earlySpring': 'Early Spring',
    'pollen.spring': 'Spring',
    'pollen.lateSpring': 'Late Spring',
    'pollen.lateSummer': 'Late Summer',
    'pollen.springSummer': 'Spring/Summer',
    'pollen.autumn': 'Fall',
    'pollen.alreadyTracked': 'You already told us about that one!',
    'pollen.addFailed': 'The computer couldn\'t save that. Try again?',
    'pollen.addSuccess': 'Got it! We\'ll keep an eye on that for you.',
    'pollen.removeFailed': 'Couldn\'t remove that. Technology, am I right?',
    'pollen.removeSuccess': 'Okay, removed!',
    
    // Footer & Cards
    'footer.dataFrom': 'Weather info from',
    'footer.disclaimer': 'Don\'t blame us if the weather\'s wrong. Even the TV weatherman gets it wrong.',
    'footer.about': 'What Is This Thing',
    'footer.blog': 'The Blog (Like a Newspaper)',
    'footer.download': 'Put It On Your Phone',
    'footer.privacy': 'Privacy Mumbo Jumbo',
    'footer.terms': 'The Fine Print',
    'footer.dataPrivacy': 'Data Thingamajig Settings',
    'footer.copyright': '© 2025-{year} Rainz. Don\'t copy our stuff.',
    'card.tenDay': 'The Next 10 Days (Probably Wrong)',
    'card.hourly': 'Hour By Hour (For The Impatient)',
    'card.hourlyTap': 'Poke any hour to see more',
    'card.showLess': 'Okay That\'s Enough',
    'card.showAll': 'Show Me Everything',
    'card.hourlyBreakdown': 'Every Single Hour',
    'card.weatherMap': 'The Weather Map Thingy',
    'card.airQuality': 'How Clean Is The Air',
    'card.sunMoon': 'Sun & Moon (Like An Almanac!)',
    'card.uvIndex': 'Sunburn-O-Meter',
    'card.sunrise': 'Sun Comes Up',
    'card.sunset': 'Sun Goes Down',
    'card.daylight': 'Hours of Daylight',
    'card.moonRise': 'Moon Comes Up',
    'card.moonSet': 'Moon Goes Down',
    'card.moonPhase': 'What The Moon Looks Like',
    'card.precipitation': 'Rain Chance',
    'card.opacity': 'See-Through-Ness',
    'card.past': 'Already Happened',
    'card.forecast': 'Coming Up',
    'card.tempHeatmap': 'The Hot & Cold Map',
    'card.windLayer': 'The Windy Map',
    'streak.day': 'day',
    'streak.days': 'days',
    'streak.current': 'Days in a row!',
    'streak.best': 'record!',
    'streak.visit': 'time',
    'streak.visits': 'times',
    'uv.low': 'Fine - Go outside, live a little',
    'uv.moderate': 'Eh - Maybe grab a hat',
    'uv.high': 'Ouch - Slather on the sunscreen',
    'uv.veryHigh': 'Yikes - Stay in the shade!',
    'uv.extreme': 'DANGER - Stay inside and watch TV',
    'language.en-GB': 'British English',
    'language.en-US': 'American English',
    'language.da': 'Dansk',
    'language.sv': 'Svenska',
    'language.no': 'Norsk',
    'language.fr': 'Français',
    'language.it': 'Italiano',
    'language.boomer': '👴 Boomer',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en-GB');
  const [userId, setUserId] = useState<string | null>(null);
  const { toast } = useToast();

  // Load language preference from database on mount
  useEffect(() => {
    const loadLanguagePreference = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        setUserId(user.id);
        const { data } = await supabase
          .from('user_preferences')
          .select('language')
          .eq('user_id', user.id)
          .maybeSingle();
        
        if (data?.language) {
          setLanguageState(data.language as Language);
        } else {
          // Fallback to localStorage if no DB preference
          const saved = localStorage.getItem('rainz-language');
          if (saved) setLanguageState(saved as Language);
        }
      } else {
        // No user, use localStorage
        const saved = localStorage.getItem('rainz-language');
        if (saved) setLanguageState(saved as Language);
      }
    };

    loadLanguagePreference();

    // Listen for auth changes
    const { data: { subscription } } = supabase.auth.onAuthStateChange((event, session) => {
      if (session?.user) {
        setUserId(session.user.id);
        loadLanguagePreference();
      } else {
        setUserId(null);
      }
    });

    return () => subscription.unsubscribe();
  }, []);

  const setLanguage = async (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('rainz-language', newLanguage);
    
    // Save to database if user is logged in
    if (userId) {
      try {
        const { error } = await supabase
          .from('user_preferences')
          .upsert({
            user_id: userId,
            language: newLanguage,
            visible_cards: { hourly: true, pollen: true, tenDay: true, routines: true, detailedMetrics: true },
            card_order: ["pollen", "hourly", "tenDay", "detailedMetrics", "routines"]
          }, {
            onConflict: 'user_id'
          });

        if (error) throw error;
      } catch (error) {
        console.error('Error saving language preference:', error);
        toast({
          title: "Could not save language preference",
          description: "Your selection will be reset when you log out.",
          variant: "destructive"
        });
      }
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export const languageFlags: Record<Language, string> = {
  'en-GB': '🇬🇧',
  'en-US': '🇺🇸',
  'da': '🇩🇰',
  'sv': '🇸🇪',
  'no': '🇳🇴',
  'fr': '🇫🇷',
  'it': '🇮🇹',
  'boomer': '👴',
};
